spring:
  cloud:
    discovery:
      enabled: false
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8081/
          predicates:
            - Path=/patient/**
        - id: r2
          uri: http://localhost:8082/
          predicates:
            - Path=/doctor/**
  application:
    name: gateway-service
server:
  port: 8889
